[package]
name = "clippy"
version = "0.0.37"
authors = [
	"Manish Goregaokar <manishsmail@gmail.com>",
	"Andre Bogus <bogusandre@gmail.com>",
	"Georg Brandl <georg@python.org>"
]
description = "A bunch of helpful lints to avoid common pitfalls in Rust"
repository = "https://github.com/Manishearth/rust-clippy"
readme = "README.md"
license = "MPL-2.0"
keywords = ["clippy", "lint", "plugin"]

[lib]
name = "clippy"
plugin = true

[dependencies]
unicode-normalization = "0.1"
semver = "0.2.1"
walkdir = "0.1"

[dev-dependencies]
compiletest_rs = "0.0.11"
regex = "0.1.47"
regex_macros = "0.1.27"
lazy_static = "0.1.15"
rustc-serialize = "0.3"

[features]

debugging = []
